### ISSUE TITLE
Instance Dies/Locks Up & Viewers Drop

### ISSUE THREAD

**Issue by HrvckRacer29** [Infinity242/KickViewBot#3]
Command Prompt errors out and instances die and the last erros are below. Happens on a powerful VPS to multiple personal pcs.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\KickViewBot-main\KickViewBotHEADLESS.py", line 56, in doTest
    self.driver.get(self.url)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 449, in get
    self.execute(Command.GET, {"url": url})
Watch now button not found on this page
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: TimedPromise timed out after 300000 ms
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5
TimeoutError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:492:5
bail@chrome://remote/content/marionette/sync.sys.mjs:211:19

**Comment by Infinity242** [comment]
Can you provide more context as to which version you're using? More information would generally be helpful.

**Comment by HrvckRacer29** [comment]
This is on the headless version. Seems to be more resource heavy then the headful version. The headful version I can have about 40 instances vs only about 15 on the headless version and eventually the headless version errors out.

**Comment by Infinity242** [comment]
Okay this is helpful to know. I will look into this, during the upcoming weekend. Thanks for letting me know!

**Comment by kalikernel** [comment]
Hi, any update on above issue?

thanks,

**Comment by HrvckRacer29** [comment]
> Okay this is helpful to know. I will look into this, during the upcoming weekend. Thanks for letting me know!

Headless version no longer works. It instantly fails upon start with the below errors over and over with how many ever threads you choose. I have tried 2 other PC's as well as the VPS where it at least worked before locking up.



Traceback (most recent call last):
Process Process-9:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\Administrator\Desktop\KickViewBot-main\KickViewBotHEADLESS.py", line 32, in doTest
    self.setupWebBrowser()
  File "C:\Users\Administrator\Desktop\KickViewBot-main\KickViewBotHEADLESS.py", line 17, in setupWebBrowser
    chrome_options = Options()
                     ^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
NameError: name 'Options' is not defined
  File "C:\Users\Administrator\Desktop\KickViewBot-main\KickViewBotHEADLESS.py", line 32, in doTest
    self.setupWebBrowser()
  File "C:\Users\Administrator\Desktop\KickViewBot-main\KickViewBotHEADLESS.py", line 17, in setupWebBrowser
    chrome_options = Options()
                     ^^^^^^^
NameError: name 'Options' is not defined
